version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medval_api
    ports:
      - "3306:3306"
    volumes:
      - my-volume:/var/lib/mysql

volumes:
  my-volume:
